name: Rust Cloudflare Worker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm i

    - name: Deploy dry run
      run: npm deploy:dry-run

    - name: Run tests
      run: npm test
